package uk.hristijan.pitstop.ui.theme

import androidx.compose.ui.graphics.Color

// British Racing Green M3 Theme Palette

// Light Scheme Colors
val BrgLightPrimary = Color(0xFF006D40)
val BrgLightOnPrimary = Color(0xFFFFFFFF)
val BrgLightPrimaryContainer = Color(0xFF96F7BB)
val BrgLightOnPrimaryContainer = Color(0xFF002110)
val BrgLightSecondary = Color(0xFF4E6355)
val BrgLightOnSecondary = Color(0xFFFFFFFF)
val BrgLightSecondaryContainer = Color(0xFFD0E9D6)
val BrgLightOnSecondaryContainer = Color(0xFF0C1F14)
val BrgLightTertiary = Color(0xFF3B6470)
val BrgLightOnTertiary = Color(0xFFFFFFFF)
val BrgLightTertiaryContainer = Color(0xFFBFE9F7)
val BrgLightOnTertiaryContainer = Color(0xFF001F27)
val BrgLightError = Color(0xFFBA1A1A)
val BrgLightOnError = Color(0xFFFFFFFF)
val BrgLightErrorContainer = Color(0xFFFFDAD6)
val BrgLightOnErrorContainer = Color(0xFF410002)
val BrgLightBackground = Color(0xFFFBFDF8)
val BrgLightOnBackground = Color(0xFF191C1A)
val BrgLightSurface = Color(0xFFFBFDF8)
val BrgLightOnSurface = Color(0xFF191C1A)
val BrgLightSurfaceVariant = Color(0xFFDCE5DD)
val BrgLightOnSurfaceVariant = Color(0xFF404942)
val BrgLightOutline = Color(0xFF717972)
val BrgLightOutlineVariant = Color(0xFFC0C9C1)

// Light Surface Containers (M3 1.2+)
val BrgLightSurfaceTint = Color(0xFF006D40)
val BrgLightSurfaceBright = Color(0xFFFBFDF8)
val BrgLightSurfaceDim = Color(0xFFD7DAD4)
val BrgLightSurfaceContainer = Color(0xFFF0F3ED)
val BrgLightSurfaceContainerLow = Color(0xFFF6F9F3)
val BrgLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val BrgLightSurfaceContainerHigh = Color(0xFFEAF0E8)
val BrgLightSurfaceContainerHighest = Color(0xFFE2EAE0)
val BrgLightInverseSurface = Color(0xFF2E312F)
val BrgLightInverseOnSurface = Color(0xFFF0F1EC)
val BrgLightInversePrimary = Color(0xFF7BDAA1)
val BrgLightScrim = Color(0xFF000000)

// Dark Scheme Colors
val BrgDarkPrimary = Color(0xFF7BDAA1)
val BrgDarkOnPrimary = Color(0xFF00391F)
val BrgDarkPrimaryContainer = Color(0xFF005232)
val BrgDarkOnPrimaryContainer = Color(0xFF96F7BB)
val BrgDarkSecondary = Color(0xFFB5CCBA)
val BrgDarkOnSecondary = Color(0xFF203528)
val BrgDarkSecondaryContainer = Color(0xFF374B3E)
val BrgDarkOnSecondaryContainer = Color(0xFFD0E9D6)
val BrgDarkTertiary = Color(0xFFA3CDDA)
val BrgDarkOnTertiary = Color(0xFF043540)
val BrgDarkTertiaryContainer = Color(0xFF224C57)
val BrgDarkOnTertiaryContainer = Color(0xFFBFE9F7)
val BrgDarkError = Color(0xFFFFB4AB)
val BrgDarkOnError = Color(0xFF690005)
val BrgDarkErrorContainer = Color(0xFF93000A)
val BrgDarkOnErrorContainer = Color(0xFFFFDAD6)
val BrgDarkBackground = Color(0xFF191C1A)
val BrgDarkOnBackground = Color(0xFFE1E3DE)
val BrgDarkSurface = Color(0xFF191C1A)
val BrgDarkOnSurface = Color(0xFFE1E3DE)
val BrgDarkSurfaceVariant = Color(0xFF404942)
val BrgDarkOnSurfaceVariant = Color(0xFFC0C9C1)
val BrgDarkOutline = Color(0xFF8A938C)
val BrgDarkOutlineVariant = Color(0xFF404942)

// Dark Surface Containers (M3 1.2+)
val BrgDarkSurfaceTint = Color(0xFF7BDAA1)
val BrgDarkSurfaceBright = Color(0xFF383A37)
val BrgDarkSurfaceDim = Color(0xFF101211)
val BrgDarkSurfaceContainer = Color(0xFF1F2220)
val BrgDarkSurfaceContainerLow = Color(0xFF191C1A)
val BrgDarkSurfaceContainerLowest = Color(0xFF0B0E0D)
val BrgDarkSurfaceContainerHigh = Color(0xFF292C2A)
val BrgDarkSurfaceContainerHighest = Color(0xFF343734)
val BrgDarkInverseSurface = Color(0xFFE1E3DE)
val BrgDarkInverseOnSurface = Color(0xFF191C1A)
val BrgDarkInversePrimary = Color(0xFF006D40)
val BrgDarkScrim = Color(0xFF000000)


